### ISSUE TITLE
Not seeing mqtt data

### ISSUE THREAD

**Issue by SCUZNUTS** [shanekuz/SPANETMCU#2]
For 'YOURMQTTSERVER' is this just the IP address and is the project assuming port 1883 for communication?

I tried IP and IP:PORT
The terminal did print 'Connected to MQTT Server' however I didnt see any new topic data on the server side show up.

One caveat to my testing is I'm powering the board off a batterybank while also plugged into the Spanet Controller because I'm still waiting on the dc-dc converter. So I'm assuming data can still be read off the spa without the 15V being consumed.

**Comment by shanekuz** [comment]
Yes just IP address of MQTT Server uses port 1883 yes

**Comment by shanekuz** [comment]
I don't know about the powering it separate sorry i would say to wait for the part as would hate to damage the spa unit.  the negative and for power and negative for serial need to be the same i think.
