### ISSUE TITLE
Missing Spa data

### ISSUE THREAD

**Issue by SCUZNUTS** [shanekuz/SPANETMCU#3]
Hi, I don't seem to be getting any spa data from my setup.
Any help appreciated. 

I'm supplying 5v fine from a dc-dc converter as seen attached.
The wifi connects fine, the webui shows up fine.
But the webui is showing 0's or off for all status's, pressing a toggle lights for example doesnt seem to do anything.

I do have an exact dc-dc buck coming, slowly, from Aliexpress.

I do see that it connects to the mqtt server and auths okay, but no topics etc show up in an mqtt browser.

![IMG_0322](https://user-images.githubusercontent.com/6490411/162553958-1bc8bc37-f364-47f9-b040-5e01fdebdcf8.jpg)

**Comment by spudooli** [comment]
I'm in the same boat. Have started to simplify the code down to just reading in the data from the spa and displaying it on the serial terminal just to start the debug process. But looking at what the weather is going to be like for the next 2 or 3 days, I won't have results to share soon.

**Comment by SCUZNUTS** [comment]
I should also note that the official wifly spanet box (the black one) still works fine when plugged back in.
I've also been trying https://github.com/wayne-love/sn_esp32 too, but different + similar issues there as well.

**Comment by shanekuz** [comment]
Try displaying on he serial terminal, disconnect the power converter and connect to PC via USB this worked for me when getting mine going as it powers from the PC and then Serial from SPA.  You should see the RF command and the stats come back on the terminal

**Comment by SCUZNUTS** [comment]
Okay so powered via USB and connected to ethernet from the Spa.

serial output after hitting the reset button on the d1;
```
{d␀d��|␀�d�<␃␄␄␌�␌l�␌#|��␃�␛�r�c�␄c��og�lgg���␄c␜p��l{d;lp�o�␘␃␌␄�␄l␌��␄␄␄c␌g�|␃�␄��␌c��no�␀l��d`␃�␒␒gg␄�␇l␏␃gr���n␄␄{r�`␃x�n�␐␃␄␌;����␜��␃␄c␌g�|␃␌�␄b��og�␀␌�d`␃�␛␒gg␄�␇l␏␃gr���n␄␄{␛l`␃␇s��o␌␌r␒l`␃�␃␄␄l���␌␌l ␃��o�␎dLoading Serial

Software serial test started

Web Server Starting
Connected to MQTT Server
Local IP: 192.168.2.138
```

Waited a couple of mins.
Still no spa data it seems.

I should also say the D5/D6 pins does have voltage between 3.3-5v and similar around the resistors so it does 'seem' to be physically connected from Spa to board.

When I measured the ethernet pin voltage it does seem to match what others have been posting;
1. 12v white orange
2. 3.3v orange
3. .2v white green
4. .2v blue
5. 3.3v white blue
6. 5v green
7. GND white brown
8. 12v brown

**Comment by shanekuz** [comment]
If you publish on MQTT to your MQTT_SERIAL_RECEIVER_CH value a RF it should dump quickly to monitor the RF data.

**Comment by shanekuz** [comment]
But should also do this evert 10sec by its self

**Comment by shanekuz** [comment]
Just to mention when i did this i connected USB to PC and then 5, 6, 7 to the NODEMCU so 7 connected to the G pin

**Comment by shanekuz** [comment]
Please also check those resistors as they dont have the same bands as my ones are they 330K?

**Comment by SCUZNUTS** [comment]
Had to check the order but yup its 330K
https://lcsc.com/product-detail/Metal-Film-Resistor-TH_TyoHM-RN-1-4W-330K-F-T-B-A1_C410629.html

I'll checkout directly connecting ethernet pin 7 to GND on board soon

**Comment by SCUZNUTS** [comment]
Hmm, still nothing coming through.

I added some bits in the 10 second loop part just to print the serial string
```
  if (currentMillis - startMillis >= period)
  {
    swSer.write("RF\n"); //Refresh SPA Data every 10 seconds
    startMillis = currentMillis;
    String inString = swSer.readString();
    Serial.println(inString);
  }
```

It just spits out new lines.
No change with ethernet GND pin 7 attached to GND on the board.

I'll probably try bypass the 'optional' resistors next.

**Comment by SCUZNUTS** [comment]
You were right to question the resistors, I'm getting data in console now. 
No data showing on the webui so far.
However I can issue commands from the webui successfully!

<img width="665" alt="image" src="https://user-images.githubusercontent.com/6490411/163297367-2cf7c350-e1ac-4297-b6a8-e226f847a22f.png">

```
RF:
,R2,102,240,34,113,0,11,49,16,4,12,2010,395,9999,1,0,731,124,20,81,464409,3813,0,0,0,0,0,29137,15610,28958,:
,R3,15,1,4,4,4,SW V4 15 09 29,SV2,16423025,20000751,1,0,0,0,0,0,NA,7,50,492,In use,61,89,7,7,111,0,:
,R4,NORM,20,20,20,4,0,577,4,76,24480,14791456,435,990,0,8388608,0,0,2,0,100,0,1,4,80,100,0,0,4,:
,R5,0,1,0,0,0,0,0,0,0,0,0,1,1,0,402,0,43,4,0,0,0,0,0,1,2,6,:
,R6,5,5,1,1,5,4,2,400,1,0,3584,5120,128,128,1792,5632,5376,2334,0,30,0,0,0,0,2,2,0,:
,R7,3082,0,1,1,166,0,2,18,9,1995,258,129,247,235,488,113,75,1,175,0,0,23,200,1,0,3,31,32,35,100,5,:
,R9,F1,0,0,0,0,0,0,0,0,0,0,0,:
,RA,F2,0,0,0,0,236,0,0,0,0,0,62720,:
,RB,F3,0,0,0,0,0,0,133,135,136,0,0,:
,RC,1,1,0,0,0,1,0,0,0,2,0,0,1,0,:
,RE,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,-4,13,30,8,5,1,0,0,0,0,0,:*
,RG,1,1,1,1,1,1,1-1-014,1-1-01,0-,0-,0-,0,:*
```

Does this data look similar to yours?

**Comment by spudooli** [comment]
Is the only change you made was to remove the resistors @SCUZNUTS?

**Comment by SCUZNUTS** [comment]
Indeed. And wire to bridge the gap.

**Comment by spudooli** [comment]
Good stuff, thanks for sharing, I'll give that a go on Saturday and report any findings.

**Comment by SCUZNUTS** [comment]
Fresh flash of the main project and everything seems operational.
Thanks for the help!

**Comment by shanekuz** [comment]
When i was building it i didnt use resistors at all i had it hard wired, but wayne-love said to use resistors so i put them in and it worked ok for me.
